const authErrors = {
  anonymous_provider_disabled: "Anonymous sign-ins are disabled.",
  bad_code_verifier: "Invalid code verifier. Please try again.",
  bad_json: "The request body is not valid JSON.",
  bad_jwt: "The authorization token is not valid.",
  bad_oauth_callback: "Invalid OAuth callback. Please try again.",
  bad_oauth_state: "Invalid OAuth state. Please try again.",
  captcha_failed: "Captcha verification failed. Please try again.",
  conflict: "A conflict occurred. Please try again later.",
  email_conflict_identity_not_deletable:
    "Email conflict. Please contact support.",
  email_exists: "This email address is already in use.",
  email_not_confirmed: "Please confirm your email address to sign in.",
  email_provider_disabled: "Email signups are disabled.",
  flow_state_expired: "Session expired. Please sign in again.",
  flow_state_not_found: "Session not found. Please sign in again.",
  hook_payload_over_size_limit: "Payload exceeds the size limit.",
  hook_timeout: "Request timed out. Please try again.",
  hook_timeout_after_retry:
    "Request timed out after retries. Please try again later.",
  identity_already_exists: "This identity is already linked to a user.",
  identity_not_found: "Identity not found.",
  insufficient_aal: "MFA required. Please complete the verification.",
  invite_not_found: "The invite is expired or already used.",
  invalid_credentials: "Invalid login credentials. Please try again.",
  manual_linking_disabled: "Manual account linking is disabled.",
  mfa_challenge_expired: "MFA challenge expired. Please request a new one.",
  mfa_factor_name_conflict: "MFA factors cannot have the same name.",
  mfa_factor_not_found: "MFA factor not found.",
  mfa_ip_address_mismatch: "IP address mismatch during MFA. Please retry.",
  mfa_verification_failed: "MFA verification failed. Please check your code.",
  mfa_verification_rejected: "MFA verification was rejected.",
  mfa_verified_factor_exists:
    "MFA factor already verified. Unenroll to continue.",
  mfa_totp_enroll_disabled: "MFA TOTP enrollment is disabled.",
  mfa_totp_verify_disabled: "MFA TOTP verification is disabled.",
  mfa_phone_enroll_disabled: "MFA phone enrollment is disabled.",
  mfa_phone_verify_disabled: "MFA phone verification is disabled.",
  no_authorization: "Authorization header is missing.",
  not_admin: "You do not have the required admin permissions.",
  oauth_provider_not_supported: "OAuth provider not supported.",
  otp_disabled: "OTP sign-in is disabled.",
  otp_expired: "OTP expired. Please request a new one.",
  over_email_send_rate_limit:
    "Too many emails sent. Please wait before trying again.",
  over_request_rate_limit:
    "Too many requests sent. Please wait before trying again.",
  over_sms_send_rate_limit:
    "Too many SMS messages sent. Please wait before trying again.",
  phone_exists: "This phone number is already in use.",
  phone_not_confirmed: "Please confirm your phone number to sign in.",
  phone_provider_disabled: "Phone signups are disabled.",
  provider_disabled: "OAuth provider is disabled.",
  provider_email_needs_verification:
    "Email verification required. Please check your email.",
  reauthentication_needed: "Please reauthenticate to proceed.",
  reauthentication_not_valid: "Reauthentication failed. Please try again.",
  request_timeout: "Request timed out. Please try again.",
  same_password: "New password cannot be the same as the old password.",
  saml_assertion_no_email: "No email found in SAML assertion.",
  saml_assertion_no_user_id: "No user ID found in SAML assertion.",
  saml_entity_id_mismatch:
    "SAML entity ID mismatch. Please check your configuration.",
  saml_idp_already_exists: "SAML identity provider already exists.",
  saml_idp_not_found: "SAML identity provider not found.",
  saml_metadata_fetch_failed:
    "Failed to fetch SAML metadata. Please check the URL.",
  saml_provider_disabled: "SAML provider is disabled.",
  saml_relay_state_expired: "SAML relay state expired. Please try again.",
  saml_relay_state_not_found:
    "SAML relay state not found. Please sign in again.",
  session_not_found: "Session not found. Please sign in again.",
  signup_disabled: "Signups are disabled on this server.",
  single_identity_not_deletable: "Cannot delete the only identity of a user.",
  sms_send_failed: "Failed to send SMS. Please check your SMS provider.",
  sso_domain_already_exists: "SSO domain already exists for this provider.",
  sso_provider_not_found: "SSO provider not found.",
  too_many_enrolled_mfa_factors:
    "Too many MFA factors enrolled. Please unenroll one.",
  unexpected_audience: "Unexpected audience in JWT.",
  unexpected_failure: "An unexpected error occurred. Please try again later.",
  user_already_exists: "A user with this information already exists.",
  user_banned: "This user is banned. Please contact support.",
  user_not_found: "User not found.",
  user_sso_managed: "Cannot update fields managed by SSO.",
  validation_failed: "Validation failed. Please check your input.",
  weak_password: "Password is too weak. Please use a stronger password.",
} as const;

export default authErrors;
